### ISSUE TITLE
Search don't working 

### ISSUE THREAD

**Issue by xdk78** [NyaaPantsu/NyaaPantsu-android-app#68]
Probably issue is related to Api changes

**Comment by akuma06** [comment]
Yeah you're right I forgot about it but it shouldn't have been deployed though :/
The fix is simple, instead of parsing a jsonarray in query, you parse it as jsonobject. And you get the jsonarray "torrents" from it.

Old response data:
`[{torrent1}, {torrent2}]`

Actual response data:
`{
Totalhits: xxx,
Torrents: [
{torrent1], {torrent2}
]
}`
Source: https://nyaa.pantsu.cat/api/search?c=&s&q=

**Comment by xdk78** [comment]
Wtf, I did nothing but now it works xd
Everything is good
